/* The following code was generated by JFlex 1.7.0 */

package analizadores;
import java_cup.runtime.Symbol;
import java.util.ArrayList;
import graficadorbarras.*;
import clases.Token;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Lexico_Reportes.jflex</tt>
 */
public class Lexico_Reportes implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  6, 41,  1,  3,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1, 19,  5,  0,  0,  0,  0,  0, 14, 15,  4,  0, 13, 10, 11,  2, 
     9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  0, 12, 18, 16, 17,  0, 
     0, 23, 38, 24, 37, 21, 40, 39, 25, 27,  7,  7, 20, 33, 34, 29, 
    36,  7, 22, 31, 35, 32, 28,  7,  7,  7,  7,  0,  0,  0,  0,  8, 
     0, 23, 38, 24, 37, 21, 40, 39, 25, 27,  7,  7, 20, 33, 34, 29, 
    36,  7, 22, 31, 35, 32, 28,  7,  7,  7,  7,  0,  1,  0,  0,  0, 
     0,  0,  0,  0,  0, 41,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\1\2\2\1\3\1\4\1\5\1\2"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\2"+
    "\3\4\1\2\2\4\1\2\4\4\1\1\2\0\1\15"+
    "\1\0\1\16\1\17\1\20\1\21\4\4\1\0\2\4"+
    "\1\0\4\4\1\1\2\0\1\22\4\4\1\0\2\4"+
    "\1\0\4\4\1\0\4\4\1\0\2\4\1\0\5\4"+
    "\1\0\3\4\1\0\2\4\2\23\2\4\1\0\2\4"+
    "\1\0\1\4\1\24\1\25\1\0\2\4\1\0\2\4"+
    "\1\0\2\4\2\26\1\0\1\4\1\0\2\4\1\0"+
    "\1\4\1\0\1\4\1\0\2\4\2\27\2\30\1\0"+
    "\1\4\2\31\2\32\2\33\1\0\1\4\2\34\1\0"+
    "\1\4\2\35";

  private static int [] zzUnpackAction() {
    int [] result = new int[140];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\124\0\322\0\374"+
    "\0\u0126\0\52\0\52\0\52\0\52\0\u0150\0\u017a\0\u01a4"+
    "\0\u01ce\0\u01f8\0\u0222\0\u024c\0\u0276\0\u02a0\0\u02ca\0\u02f4"+
    "\0\u031e\0\u0348\0\u0372\0\u039c\0\u03c6\0\u03f0\0\250\0\52"+
    "\0\u041a\0\52\0\52\0\52\0\52\0\u0444\0\u046e\0\u0498"+
    "\0\u04c2\0\u04ec\0\u0516\0\u0540\0\u056a\0\u0594\0\u05be\0\u05e8"+
    "\0\u0612\0\52\0\u063c\0\u0666\0\u041a\0\u0690\0\u06ba\0\u06e4"+
    "\0\u070e\0\u0738\0\u0762\0\u078c\0\u07b6\0\u07e0\0\u080a\0\u0834"+
    "\0\u085e\0\u0888\0\u08b2\0\u08dc\0\u0906\0\u0930\0\u095a\0\u0984"+
    "\0\u09ae\0\u09d8\0\u0a02\0\u0a2c\0\u0a56\0\u0a80\0\u0aaa\0\u0ad4"+
    "\0\u0afe\0\u0b28\0\u0b52\0\u0b7c\0\u0ba6\0\u0bd0\0\52\0\322"+
    "\0\u0bfa\0\u0c24\0\u0c4e\0\u0c78\0\u0ca2\0\u0ccc\0\u0cf6\0\322"+
    "\0\u0d20\0\u0d4a\0\u0d74\0\u0d9e\0\u0dc8\0\u0df2\0\u0e1c\0\u0e46"+
    "\0\u0e70\0\u0e9a\0\52\0\322\0\u0ec4\0\u0eee\0\u0f18\0\u0f42"+
    "\0\u0f6c\0\u0f96\0\u0fc0\0\u0fea\0\u1014\0\u103e\0\u1068\0\u1092"+
    "\0\52\0\322\0\52\0\322\0\u10bc\0\u10e6\0\52\0\322"+
    "\0\52\0\322\0\52\0\322\0\u1110\0\u113a\0\52\0\322"+
    "\0\u1164\0\u118e\0\52\0\322";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[140];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\3\1\2\1\5\1\6\1\7"+
    "\1\2\1\10\1\11\1\2\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\2\7\1\23\1\24"+
    "\1\7\1\25\1\26\1\7\1\27\1\30\1\31\2\7"+
    "\1\32\1\7\1\33\2\7\1\34\1\7\54\0\1\3"+
    "\1\0\1\3\2\0\1\3\45\0\1\35\1\0\1\36"+
    "\45\0\5\37\1\40\1\0\43\37\7\0\3\7\12\0"+
    "\6\7\1\0\3\7\1\0\12\7\12\0\1\10\1\0"+
    "\1\41\47\0\1\10\60\0\1\42\51\0\1\43\51\0"+
    "\1\44\51\0\1\45\40\0\3\7\12\0\1\7\1\46"+
    "\4\7\1\0\3\7\1\0\12\7\10\0\3\7\12\0"+
    "\2\7\1\47\3\7\1\0\3\7\1\0\12\7\10\0"+
    "\3\7\12\0\3\7\1\50\2\7\1\0\2\7\1\51"+
    "\1\0\12\7\42\0\1\52\17\0\3\7\12\0\6\7"+
    "\1\0\3\7\1\0\2\7\1\53\7\7\10\0\3\7"+
    "\12\0\6\7\1\0\3\7\1\0\7\7\1\54\2\7"+
    "\41\0\1\55\20\0\3\7\12\0\6\7\1\0\3\7"+
    "\1\0\1\7\1\56\10\7\10\0\3\7\12\0\6\7"+
    "\1\0\3\7\1\0\1\7\1\57\10\7\10\0\3\7"+
    "\12\0\2\7\1\60\3\7\1\0\3\7\1\0\12\7"+
    "\10\0\3\7\12\0\2\7\1\61\3\7\1\0\3\7"+
    "\1\0\12\7\1\0\3\35\1\62\2\35\1\62\43\35"+
    "\4\63\1\64\45\63\11\0\1\65\47\0\3\7\12\0"+
    "\1\7\1\66\4\7\1\0\3\7\1\0\12\7\10\0"+
    "\3\7\12\0\4\7\1\67\1\7\1\0\3\7\1\0"+
    "\12\7\10\0\3\7\12\0\6\7\1\0\3\7\1\0"+
    "\6\7\1\70\3\7\10\0\3\7\12\0\6\7\1\0"+
    "\3\7\1\0\3\7\1\71\6\7\45\0\1\72\14\0"+
    "\3\7\12\0\6\7\1\0\3\7\1\0\5\7\1\73"+
    "\4\7\10\0\3\7\12\0\6\7\1\0\3\7\1\0"+
    "\4\7\1\74\5\7\42\0\1\75\17\0\3\7\12\0"+
    "\6\7\1\0\3\7\1\0\2\7\1\76\7\7\10\0"+
    "\3\7\12\0\6\7\1\0\3\7\1\0\2\7\1\77"+
    "\7\7\10\0\3\7\12\0\6\7\1\0\2\7\1\100"+
    "\1\0\12\7\10\0\3\7\12\0\3\7\1\101\2\7"+
    "\1\0\3\7\1\0\12\7\1\0\4\63\1\102\45\63"+
    "\2\0\1\62\1\0\1\64\54\0\3\7\12\0\2\7"+
    "\1\103\3\7\1\0\3\7\1\0\12\7\10\0\3\7"+
    "\12\0\5\7\1\104\1\0\3\7\1\0\12\7\10\0"+
    "\3\7\12\0\1\7\1\105\4\7\1\0\3\7\1\0"+
    "\12\7\10\0\3\7\12\0\6\7\1\0\3\7\1\0"+
    "\4\7\1\106\5\7\27\0\1\107\32\0\3\7\12\0"+
    "\2\7\1\110\3\7\1\0\3\7\1\0\12\7\10\0"+
    "\3\7\12\0\1\7\1\111\4\7\1\0\3\7\1\0"+
    "\12\7\30\0\1\112\31\0\3\7\12\0\3\7\1\113"+
    "\2\7\1\0\3\7\1\0\12\7\10\0\3\7\12\0"+
    "\1\7\1\114\4\7\1\0\3\7\1\0\12\7\10\0"+
    "\3\7\12\0\6\7\1\0\3\7\1\0\2\7\1\115"+
    "\7\7\10\0\3\7\12\0\6\7\1\0\3\7\1\0"+
    "\11\7\1\116\1\0\2\63\1\62\1\63\1\102\45\63"+
    "\7\0\3\7\12\0\3\7\1\117\2\7\1\0\3\7"+
    "\1\0\12\7\10\0\3\7\12\0\6\7\1\120\1\121"+
    "\2\7\1\0\12\7\10\0\3\7\12\0\6\7\1\0"+
    "\3\7\1\0\3\7\1\122\6\7\10\0\3\7\12\0"+
    "\3\7\1\123\2\7\1\0\3\7\1\0\12\7\33\0"+
    "\2\124\25\0\3\7\12\0\6\7\1\124\1\125\2\7"+
    "\1\0\12\7\10\0\3\7\12\0\6\7\1\0\3\7"+
    "\1\0\3\7\1\126\6\7\27\0\1\127\32\0\3\7"+
    "\12\0\2\7\1\130\3\7\1\0\3\7\1\0\12\7"+
    "\10\0\3\7\12\0\2\7\1\131\3\7\1\0\3\7"+
    "\1\0\12\7\10\0\3\7\12\0\1\7\1\132\4\7"+
    "\1\0\3\7\1\0\12\7\10\0\3\7\12\0\6\7"+
    "\1\133\1\134\2\7\1\0\12\7\10\0\3\7\12\0"+
    "\2\7\1\135\3\7\1\0\3\7\1\0\12\7\35\0"+
    "\1\136\24\0\3\7\12\0\6\7\1\0\1\7\1\137"+
    "\1\7\1\0\12\7\10\0\3\7\12\0\3\7\1\140"+
    "\2\7\1\0\3\7\1\0\12\7\10\0\3\7\12\0"+
    "\2\7\1\141\3\7\1\0\3\7\1\0\12\7\42\0"+
    "\1\142\17\0\3\7\12\0\6\7\1\0\3\7\1\0"+
    "\2\7\1\143\7\7\10\0\3\7\12\0\1\7\1\144"+
    "\4\7\1\0\3\7\1\0\12\7\10\0\3\7\12\0"+
    "\6\7\1\145\1\146\2\7\1\0\12\7\10\0\3\7"+
    "\12\0\6\7\1\0\3\7\1\0\6\7\1\147\3\7"+
    "\31\0\1\150\30\0\3\7\12\0\4\7\1\151\1\7"+
    "\1\0\3\7\1\0\12\7\10\0\3\7\12\0\4\7"+
    "\1\152\1\7\1\0\3\7\1\0\12\7\36\0\1\153"+
    "\23\0\3\7\12\0\6\7\1\0\2\7\1\154\1\0"+
    "\12\7\10\0\3\7\12\0\6\7\1\0\3\7\1\155"+
    "\1\156\11\7\33\0\2\157\25\0\3\7\12\0\6\7"+
    "\1\157\1\160\2\7\1\0\12\7\10\0\3\7\12\0"+
    "\2\7\1\161\3\7\1\0\3\7\1\0\12\7\31\0"+
    "\1\162\30\0\3\7\12\0\4\7\1\163\1\7\1\0"+
    "\3\7\1\0\12\7\10\0\3\7\12\0\6\7\1\164"+
    "\1\165\2\7\1\0\12\7\30\0\1\166\31\0\3\7"+
    "\12\0\3\7\1\167\2\7\1\0\3\7\1\0\12\7"+
    "\10\0\3\7\12\0\5\7\1\170\1\0\3\7\1\0"+
    "\12\7\33\0\2\171\25\0\3\7\12\0\6\7\1\171"+
    "\1\172\2\7\1\0\12\7\27\0\1\173\32\0\3\7"+
    "\12\0\2\7\1\174\3\7\1\0\3\7\1\0\12\7"+
    "\10\0\3\7\12\0\6\7\1\0\3\7\1\175\1\176"+
    "\11\7\36\0\1\177\23\0\3\7\12\0\6\7\1\0"+
    "\2\7\1\200\1\0\12\7\36\0\1\201\23\0\3\7"+
    "\12\0\6\7\1\0\2\7\1\202\1\0\12\7\27\0"+
    "\1\203\32\0\3\7\12\0\2\7\1\204\3\7\1\0"+
    "\3\7\1\0\12\7\10\0\3\7\12\0\6\7\1\205"+
    "\1\206\2\7\1\0\12\7\33\0\2\207\25\0\3\7"+
    "\12\0\6\7\1\207\1\210\2\7\1\0\12\7\35\0"+
    "\1\211\24\0\3\7\12\0\6\7\1\0\1\7\1\212"+
    "\1\7\1\0\12\7\36\0\1\213\23\0\3\7\12\0"+
    "\6\7\1\0\2\7\1\214\1\0\12\7\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4536];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\7\1\4\11\20\1\2\0\1\11\1\0"+
    "\4\11\4\1\1\0\2\1\1\0\4\1\1\11\2\0"+
    "\5\1\1\0\2\1\1\0\4\1\1\0\4\1\1\0"+
    "\2\1\1\0\5\1\1\0\3\1\1\0\2\1\1\11"+
    "\3\1\1\0\2\1\1\0\3\1\1\0\2\1\1\0"+
    "\2\1\1\0\2\1\1\11\1\1\1\0\1\1\1\0"+
    "\2\1\1\0\1\1\1\0\1\1\1\0\2\1\1\11"+
    "\1\1\1\11\1\1\1\0\1\1\1\11\1\1\1\11"+
    "\1\1\1\11\1\1\1\0\1\1\1\11\1\1\1\0"+
    "\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[140];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public void agregarError(String lexema, String tipo){
        String linea, columna;
        linea = Integer.toString(yyline);
        columna = Integer.toString(yycolumn);
        graficadorbarras.GraficadorBarras.erroresLexicos.add(new Token(0,lexema, tipo, linea, columna));
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico_Reportes(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { 
            } 
            // fall through
          case 30: break;
          case 2: 
            { System.out.println("Error lexico "+ yytext() +" linea No: "+ yyline+ " columna: " +yychar); 
    agregarError(yytext(), "Lexico en archivo de reportes");
            } 
            // fall through
          case 31: break;
          case 3: 
            { yychar=1;
            } 
            // fall through
          case 32: break;
          case 4: 
            { return new Symbol(sym.identificador,yyline,yychar, yytext());
            } 
            // fall through
          case 33: break;
          case 5: 
            { return new Symbol(sym.num,yyline,yychar, yytext());
            } 
            // fall through
          case 34: break;
          case 6: 
            { return new Symbol(sym.puntocoma,yyline,yychar, yytext());
            } 
            // fall through
          case 35: break;
          case 7: 
            { return new Symbol(sym.coma,yyline,yychar, yytext());
            } 
            // fall through
          case 36: break;
          case 8: 
            { return new Symbol(sym.parentesisA,yyline,yychar, yytext());
            } 
            // fall through
          case 37: break;
          case 9: 
            { return new Symbol(sym.parentesisC,yyline,yychar, yytext());
            } 
            // fall through
          case 38: break;
          case 10: 
            { return new Symbol(sym.igual,yyline,yychar, yytext());
            } 
            // fall through
          case 39: break;
          case 11: 
            { return new Symbol(sym.mayor,yyline,yychar, yytext());
            } 
            // fall through
          case 40: break;
          case 12: 
            { return new Symbol(sym.menor,yyline,yychar, yytext());
            } 
            // fall through
          case 41: break;
          case 13: 
            { return new Symbol(sym.cadena,yyline,yychar, yytext());
            } 
            // fall through
          case 42: break;
          case 14: 
            { return new Symbol(sym.igualigual,yyline,yychar, yytext());
            } 
            // fall through
          case 43: break;
          case 15: 
            { return new Symbol(sym.mayorigual,yyline,yychar, yytext());
            } 
            // fall through
          case 44: break;
          case 16: 
            { return new Symbol(sym.menorigual,yyline,yychar, yytext());
            } 
            // fall through
          case 45: break;
          case 17: 
            { return new Symbol(sym.noigual,yyline,yychar, yytext());
            } 
            // fall through
          case 46: break;
          case 18: 
            { return new Symbol(sym.decimal,yyline,yychar, yytext());
            } 
            // fall through
          case 47: break;
          case 19: 
            { return new Symbol(sym.sumar,yyline,yychar, yytext());
            } 
            // fall through
          case 48: break;
          case 20: 
            { return new Symbol(sym.tipoCadena,yyline,yychar, yytext());
            } 
            // fall through
          case 49: break;
          case 21: 
            { return new Symbol(sym.contar,yyline,yychar, yytext());
            } 
            // fall through
          case 50: break;
          case 22: 
            { return new Symbol(sym.archivo,yyline,yychar, yytext());
            } 
            // fall through
          case 51: break;
          case 23: 
            { return new Symbol(sym.contarsi,yyline,yychar, yytext());
            } 
            // fall through
          case 52: break;
          case 24: 
            { return new Symbol(sym.imprimir,yyline,yychar, yytext());
            } 
            // fall through
          case 53: break;
          case 25: 
            { return new Symbol(sym.numerico,yyline,yychar, yytext());
            } 
            // fall through
          case 54: break;
          case 26: 
            { return new Symbol(sym.promedio,yyline,yychar, yytext());
            } 
            // fall through
          case 55: break;
          case 27: 
            { return new Symbol(sym.graficar,yyline,yychar, yytext());
            } 
            // fall through
          case 56: break;
          case 28: 
            { return new Symbol(sym.obtenersi,yyline,yychar, yytext());
            } 
            // fall through
          case 57: break;
          case 29: 
            { return new Symbol(sym.leerarchivo,yyline,yychar, yytext());
            } 
            // fall through
          case 58: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
