
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

import java_cup.runtime.*;
import graficadorbarras.*;
import clases.*;
import java.util.HashMap;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\042\000\002\002\004\000\002\002\004\000\002\002" +
    "\004\000\002\002\004\000\002\002\003\000\002\002\003" +
    "\000\002\002\003\000\002\004\007\000\002\005\005\000" +
    "\002\005\003\000\002\006\003\000\002\006\003\000\002" +
    "\006\003\000\002\006\003\000\002\003\007\000\002\007" +
    "\003\000\002\007\003\000\002\007\003\000\002\012\006" +
    "\000\002\012\010\000\002\012\006\000\002\012\010\000" +
    "\002\012\014\000\002\012\014\000\002\011\017\000\002" +
    "\013\003\000\002\013\003\000\002\013\003\000\002\010" +
    "\003\000\002\010\003\000\002\010\003\000\002\010\003" +
    "\000\002\010\003\000\002\010\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\133\000\014\004\005\005\012\006\014\015\015\016" +
    "\007\001\002\000\016\002\ufffd\004\ufffd\005\ufffd\006\ufffd" +
    "\015\ufffd\016\ufffd\001\002\000\004\032\ufff2\001\002\000" +
    "\016\002\133\004\005\005\012\006\014\015\015\016\007" +
    "\001\002\000\004\030\117\001\002\000\016\002\ufffc\004" +
    "\ufffc\005\ufffc\006\ufffc\015\ufffc\016\ufffc\001\002\000\016" +
    "\002\ufffb\004\ufffb\005\ufffb\006\ufffb\015\ufffb\016\ufffb\001" +
    "\002\000\004\032\ufff1\001\002\000\004\032\032\001\002" +
    "\000\004\032\ufff0\001\002\000\004\030\016\001\002\000" +
    "\004\035\017\001\002\000\004\025\020\001\002\000\004" +
    "\035\021\001\002\000\004\025\022\001\002\000\004\032" +
    "\023\001\002\000\004\025\024\001\002\000\004\035\025" +
    "\001\002\000\004\025\026\001\002\000\004\035\027\001" +
    "\002\000\004\031\030\001\002\000\004\026\031\001\002" +
    "\000\016\002\uffe9\004\uffe9\005\uffe9\006\uffe9\015\uffe9\016" +
    "\uffe9\001\002\000\004\027\033\001\002\000\016\007\036" +
    "\010\035\011\037\012\034\013\042\014\041\001\002\000" +
    "\004\030\112\001\002\000\004\030\105\001\002\000\004" +
    "\030\102\001\002\000\004\030\077\001\002\000\004\026" +
    "\076\001\002\000\004\030\065\001\002\000\004\030\043" +
    "\001\002\000\004\032\044\001\002\000\004\025\045\001" +
    "\002\000\004\035\046\001\002\000\004\025\047\001\002" +
    "\000\016\017\052\020\054\021\055\022\053\023\050\024" +
    "\051\001\002\000\004\025\uffe1\001\002\000\004\025\uffe0" +
    "\001\002\000\004\025\uffe5\001\002\000\004\025\uffe2\001" +
    "\002\000\004\025\uffe4\001\002\000\004\025\uffe3\001\002" +
    "\000\004\025\057\001\002\000\010\033\062\034\060\035" +
    "\061\001\002\000\004\031\uffe7\001\002\000\004\031\uffe6" +
    "\001\002\000\004\031\uffe8\001\002\000\004\031\064\001" +
    "\002\000\004\026\uffeb\001\002\000\004\032\066\001\002" +
    "\000\004\025\067\001\002\000\004\035\070\001\002\000" +
    "\004\025\071\001\002\000\016\017\052\020\054\021\055" +
    "\022\053\023\050\024\051\001\002\000\004\025\073\001" +
    "\002\000\010\033\062\034\060\035\061\001\002\000\004" +
    "\031\075\001\002\000\004\026\uffea\001\002\000\016\002" +
    "\ufff3\004\ufff3\005\ufff3\006\ufff3\015\ufff3\016\ufff3\001\002" +
    "\000\004\032\100\001\002\000\004\031\101\001\002\000" +
    "\004\026\uffed\001\002\000\004\035\103\001\002\000\004" +
    "\031\104\001\002\000\004\026\uffef\001\002\000\004\032" +
    "\106\001\002\000\004\025\107\001\002\000\004\035\110" +
    "\001\002\000\004\031\111\001\002\000\004\026\uffee\001" +
    "\002\000\004\032\113\001\002\000\004\025\114\001\002" +
    "\000\004\035\115\001\002\000\004\031\116\001\002\000" +
    "\004\026\uffec\001\002\000\012\032\123\033\122\034\120" +
    "\035\121\001\002\000\006\025\ufff4\031\ufff4\001\002\000" +
    "\006\025\ufff6\031\ufff6\001\002\000\006\025\ufff5\031\ufff5" +
    "\001\002\000\006\025\ufff7\031\ufff7\001\002\000\006\025" +
    "\126\031\127\001\002\000\006\025\ufff8\031\ufff8\001\002" +
    "\000\012\032\123\033\122\034\120\035\121\001\002\000" +
    "\004\026\130\001\002\000\016\002\ufffa\004\ufffa\005\ufffa" +
    "\006\ufffa\015\ufffa\016\ufffa\001\002\000\006\025\ufff9\031" +
    "\ufff9\001\002\000\016\002\ufffe\004\ufffe\005\ufffe\006\ufffe" +
    "\015\ufffe\016\ufffe\001\002\000\004\002\001\001\002\000" +
    "\016\002\000\004\000\005\000\006\000\015\000\016\000" +
    "\001\002\000\016\002\uffff\004\uffff\005\uffff\006\uffff\015" +
    "\uffff\016\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\133\000\014\002\005\003\007\004\010\007\012\011" +
    "\003\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\003\133\004\134\007\012\011\131\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\012\037\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\010" +
    "\055\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\013\062\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\010\071\001" +
    "\001\000\002\001\001\000\004\013\073\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\005\123" +
    "\006\124\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\006\130\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public String salida = "";
    /**
    * Metodo para error sintactico
    **/
    HashMap variables = graficadorbarras.GraficadorBarras.variables;
    public void agregarVariable(String id, Object objeto){
        graficadorbarras.GraficadorBarras.variables.put(id,objeto);
    }
    public void errorSemantico(String tipo){
        graficadorbarras.GraficadorBarras.erroresSemanticos.add("Error semantico en el archivo de reportes " + tipo);  
    }
    public void syntax_error(Symbol s){
        System.err.println("Error sintacto línea " + (s.left) +" columna "+s.right+ ". No se esperaba " +s.value+"."); 
            graficadorbarras.GraficadorBarras.erroresSintacticos.add(new Token(0,s.value.toString(), "Sintactico en archivo de datos", Integer.toString(s.left), Integer.toString(s.right)));
        }
    
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        //System.err.println("Error irrecuperable en la linea " + (s.left)+ " columna " +s.right+". Elemento " + s.value + " no reconocido.");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= REP EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // REP ::= REP VAR 
            {
              String RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("REP",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // REP ::= REP IMP 
            {
              String RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("REP",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // REP ::= REP GRA 
            {
              String RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("REP",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // REP ::= GRA 
            {
              String RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("REP",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // REP ::= VAR 
            {
              String RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("REP",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // REP ::= IMP 
            {
              String RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("REP",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // IMP ::= imprimir parentesisA EXP parentesisC puntocoma 
            {
              String RESULT =null;
		int expresionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int expresionright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String expresion = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		System.out.println(expresion);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("IMP",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // EXP ::= EXP coma EXPDA 
            {
              String RESULT =null;
		int txtleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int txtright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String txt = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int textoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int textoright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String texto = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		if(!texto.equals("M@1")){
            RESULT = txt + texto;
        }else{
            RESULT = txt;
        }
              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXP",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // EXP ::= EXPDA 
            {
              String RESULT =null;
		int textoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int textoright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String texto = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		if(!texto.equals("M@1")){
            RESULT = texto;
        }else{
            RESULT = "";
        }
              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXP",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // EXPDA ::= identificador 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            Object variable = variables.get(id);
            int contador = 0;
            if(variable != null){
                String result = "";
                if(variable instanceof ArchivoDatos){
                    
                    
                }else{
                    result += variable;
                    /*System.out.println("el tipo de la variable "+id);
                    errorSemantico("el tipo de la variable "+id);
                    RESULT = "M@1";*/
                }
                RESULT = result;
            }else{
                System.out.println("la variable "+id+" no existe");
                errorSemantico("la variable "+id+" no existe");
                RESULT = "M@1";
            }
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPDA",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // EXPDA ::= cadena 
            {
              String RESULT =null;
		int cadenaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cadenaright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String cadena = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = cadena.replace("\"", "");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPDA",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // EXPDA ::= num 
            {
              String RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String num = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		String result = "" + num; RESULT = result;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPDA",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // EXPDA ::= decimal 
            {
              String RESULT =null;
		int decimalleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int decimalright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String decimal = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		String result = "" + decimal; RESULT = result;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPDA",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // VAR ::= TIPO identificador igual FUN puntocoma 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int funcionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int funcionright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object funcion = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
            if(funcion instanceof Integer){
                if((Integer)funcion != -1){
                    agregarVariable(id,funcion);
                }
            }else{
                agregarVariable(id,funcion);
            }
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VAR",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // TIPO ::= numerico 
            {
              String RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("TIPO",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // TIPO ::= tipoCadena 
            {
              String RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("TIPO",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // TIPO ::= archivo 
            {
              String RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("TIPO",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // FUN ::= leerarchivo parentesisA cadena parentesisC 
            {
              Object RESULT =null;
		int rutaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int rutaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String ruta = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		AnalizarDatos analizar = new AnalizarDatos(); ruta.replace("\"",""); ArchivoDatos archivo = analizar.analisis(ruta);
              if(archivo == null){
                RESULT = 1;
              }else{
                RESULT = archivo;
              }
              CUP$parser$result = parser.getSymbolFactory().newSymbol("FUN",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // FUN ::= sumar parentesisA identificador coma cadena parentesisC 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int claveleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int claveright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String clave = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                ArchivoDatos sumar;
                Object variable = variables.get(id);
                int contador = 0;
                if(variable != null){
                    if(variable instanceof ArchivoDatos){
                        sumar = (ArchivoDatos)variable;
                        for(Clave x:sumar.claves){
                            if(x.clave.equals(clave)){
                                break;
                            }
                            contador++;
                        }
                        double suma = 0;
                        for(Registro x:sumar.registros){
                            if(x.datos.get(contador).tipo == 0){
                                suma += x.datos.get(contador).num;
                            }else if(x.datos.get(contador).tipo==1){
                                suma += x.datos.get(contador).decimal;
                            }else{
                                
                            }
                        }
                        RESULT = suma;
                    }else{
                        System.out.println("la variable "+id+" no es de tipo archivo");
                        errorSemantico("la variable "+id+" no es de tipo archivo");
                        RESULT = -1;
                    }
                }else{
                    System.out.println("la variable "+id+" no existe");
                    errorSemantico("la variable "+id+"no existe");
                    RESULT = -1;
                }
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("FUN",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // FUN ::= contar parentesisA identificador parentesisC 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		ArchivoDatos sumar;
                Object variable = variables.get(id);
                if(variable != null){
                    if(variable instanceof ArchivoDatos){
                        sumar = (ArchivoDatos)variable;
                        RESULT = sumar.registros.size();
                    }else{
                        System.out.println("la variable "+id+" no es de tipo archivo");
                        errorSemantico("la variable "+id+" no es de tipo archivo");
                        RESULT = -1;
                    }
                }else{
                    System.out.println("la variable "+id+" no existe");
                    errorSemantico("la variable "+id+"no existe");
                    RESULT = -1;
                }
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("FUN",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // FUN ::= promedio parentesisA identificador coma cadena parentesisC 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int claveleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int claveright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String clave = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                ArchivoDatos sumar;
                Object variable = variables.get(id);
                int contador = 0;
                if(variable != null){
                    if(variable instanceof ArchivoDatos){
                        sumar = (ArchivoDatos)variable;
                        for(Clave x:sumar.claves){
                            if(x.clave.equals(clave)){
                                break;
                            }
                            contador++;
                        }
                        double suma = 0;
                        for(Registro x:sumar.registros){
                            if(x.datos.get(contador).tipo == 0){
                                suma += x.datos.get(contador).num;
                            }else if(x.datos.get(contador).tipo==1){
                                suma += x.datos.get(contador).decimal;
                            }else{
                                
                            }
                        }
                        RESULT = suma/sumar.registros.size();
                    }else{
                        System.out.println("la variable "+id+" no es de tipo archivo");
                        errorSemantico("la variable "+id+" no es de tipo archivo");
                        RESULT = -1;
                    }
                }else{
                    System.out.println("la variable "+id+" no existe");
                    errorSemantico("la variable "+id+"no existe");
                    RESULT = -1;
                }
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("FUN",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // FUN ::= contarsi parentesisA identificador coma cadena coma OPERADOR coma DATOS parentesisC 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int claveleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int claveright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String clave = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int opeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int operight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String ope = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int datoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int datoright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Dato dato = (Dato)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                ArchivoDatos contarSi;
                Object variable = variables.get(id);
                int contador = 0;
                int conteo = 0;
                if(variable != null){
                    if(variable instanceof ArchivoDatos){
                        contarSi = (ArchivoDatos)variable;
                        for(Clave x:contarSi.claves){
                            if(x.clave.equals(clave)){
                                break;
                            }
                            contador++;
                        }
                        if(ope.equals("0")){// ">"
                            if(dato.tipo == 2){
                                errorSemantico("el dato a comparar no es del tipo correcto");
                            }else{
                                for(Registro x:contarSi.registros){
                                    if(x.datos.get(contador).tipo == 0){
                                        if(dato.tipo == 0){
                                            if(x.datos.get(contador).num > dato.num){
                                                conteo++;
                                            }
                                        }else if(dato.tipo == 1){
                                            if(x.datos.get(contador).num > dato.decimal){
                                                conteo++;
                                            }
                                        }
                                    }else if(x.datos.get(contador).tipo==1){
                                        if(dato.tipo == 0){
                                            if(x.datos.get(contador).decimal > dato.num){
                                                conteo++;
                                            }
                                        }else if(dato.tipo == 1){
                                            if(x.datos.get(contador).decimal > dato.decimal){
                                                conteo++;
                                            }
                                        }
                                    }else{

                                    }
                                } 
                            }
                        }else if(ope.equals("1")){//"<"
                            if(dato.tipo == 2){
                                errorSemantico("el dato a comparar no es del tipo correcto");
                            }else{
                                for(Registro x:contarSi.registros){
                                    if(x.datos.get(contador).tipo == 0){
                                        if(dato.tipo == 0){
                                            if(x.datos.get(contador).num < dato.num){
                                                conteo++;
                                            }
                                        }else if(dato.tipo == 1){
                                            if(x.datos.get(contador).num < dato.decimal){
                                                conteo++;
                                            }
                                        }
                                    }else if(x.datos.get(contador).tipo==1){
                                        if(dato.tipo == 0){
                                            if(x.datos.get(contador).decimal < dato.num){
                                                conteo++;
                                            }
                                        }else if(dato.tipo == 1){
                                            if(x.datos.get(contador).decimal < dato.decimal){
                                                conteo++;
                                            }
                                        }
                                    }else{

                                    }
                                } 
                            }
                        }else if(ope.equals("2")){//">="
                            if(dato.tipo == 2){
                                errorSemantico("el dato a comparar no es del tipo correcto");
                            }else{
                                for(Registro x:contarSi.registros){
                                    if(x.datos.get(contador).tipo == 0){
                                        if(dato.tipo == 0){
                                            if(x.datos.get(contador).num >= dato.num){
                                                conteo++;
                                            }
                                        }else if(dato.tipo == 1){
                                            if(x.datos.get(contador).num >= dato.decimal){
                                                conteo++;
                                            }
                                        }
                                    }else if(x.datos.get(contador).tipo==1){
                                        if(dato.tipo == 0){
                                            if(x.datos.get(contador).decimal >= dato.num){
                                                conteo++;
                                            }
                                        }else if(dato.tipo == 1){
                                            if(x.datos.get(contador).decimal >= dato.decimal){
                                                conteo++;
                                            }
                                        }
                                    }else{

                                    }
                                } 
                            }
                        }else if(ope.equals("3")){//"<="
                            if(dato.tipo == 2){
                                errorSemantico("el dato a comparar no es del tipo correcto");
                            }else{
                                for(Registro x:contarSi.registros){
                                    if(x.datos.get(contador).tipo == 0){
                                        if(dato.tipo == 0){
                                            if(x.datos.get(contador).num <= dato.num){
                                                conteo++;
                                            }
                                        }else if(dato.tipo == 1){
                                            if(x.datos.get(contador).num <= dato.decimal){
                                                conteo++;
                                            }
                                        }
                                    }else if(x.datos.get(contador).tipo==1){
                                        if(dato.tipo == 0){
                                            if(x.datos.get(contador).decimal <= dato.num){
                                                conteo++;
                                            }
                                        }else if(dato.tipo == 1){
                                            if(x.datos.get(contador).decimal <= dato.decimal){
                                                conteo++;
                                            }
                                        }
                                    }else{

                                    }
                                } 
                            }
                        }else if(ope.equals("4")){//"=="
                            for(Registro x:contarSi.registros){
                                if(x.datos.get(contador).tipo == 0){
                                    if(dato.tipo == 0){
                                        if(x.datos.get(contador).num == dato.num){
                                            conteo++;
                                        }
                                    }else if(dato.tipo == 1){
                                        if(x.datos.get(contador).num == dato.decimal){
                                            conteo++;
                                        }
                                    }else if(dato.tipo == 2){
                                        errorSemantico("comparacion entre cadena y numero");
                                    }
                                }else if(x.datos.get(contador).tipo==1){
                                    if(dato.tipo == 0){
                                        if(x.datos.get(contador).decimal == dato.num){
                                            conteo++;
                                        }
                                    }else if(dato.tipo == 1){
                                        if(x.datos.get(contador).decimal == dato.decimal){
                                            conteo++;
                                        }
                                    }else if(dato.tipo == 2){
                                        errorSemantico("comparacion entre cadena y decimal");
                                    }
                                }else{
                                    if(dato.tipo == 0){
                                        errorSemantico("comparacion entre cadena y numero");
                                    }else if(dato.tipo == 1){
                                        errorSemantico("comparacion entre cadena y decimal");
                                    }else if(dato.tipo == 2){
                                        if(x.datos.get(contador).cadena.equals(dato.cadena)){
                                            conteo++;
                                        }
                                    }
                                }
                            }
                        }else if(ope.equals("5")){//!=
                            for(Registro x:contarSi.registros){
                                if(x.datos.get(contador).tipo == 0){
                                    if(dato.tipo == 0){
                                        if(x.datos.get(contador).num != dato.num){
                                            conteo++;
                                        }
                                    }else if(dato.tipo == 1){
                                        if(x.datos.get(contador).num != dato.decimal){
                                            conteo++;
                                        }
                                    }else if(dato.tipo == 2){
                                        errorSemantico("comparacion entre cadena y numero");
                                    }
                                }else if(x.datos.get(contador).tipo==1){
                                    if(dato.tipo == 0){
                                        if(x.datos.get(contador).decimal != dato.num){
                                            conteo++;
                                        }
                                    }else if(dato.tipo == 1){
                                        if(x.datos.get(contador).decimal != dato.decimal){
                                            conteo++;
                                        }
                                    }else if(dato.tipo == 2){
                                        errorSemantico("comparacion entre cadena y decimal");
                                    }
                                }else{
                                    if(dato.tipo == 0){
                                        errorSemantico("comparacion entre cadena y numero");
                                    }else if(dato.tipo == 1){
                                        errorSemantico("comparacion entre cadena y decimal");
                                    }else if(dato.tipo == 2){
                                        if(!x.datos.get(contador).cadena.equals(dato.cadena)){
                                            conteo++;
                                        }
                                    }
                                }
                            }
                        }
                        RESULT = conteo;
                    }else{
                        System.out.println("la variable "+id+" no es de tipo archivo");
                        errorSemantico("la variable "+id+" no es de tipo archivo");
                        RESULT = -1;
                    }
                }else{
                    System.out.println("la variable "+id+" no existe");
                    errorSemantico("la variable "+id+"no existe");
                    RESULT = -1;
                }
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("FUN",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // FUN ::= obtenersi parentesisA identificador coma cadena coma OPERADOR coma DATOS parentesisC 
            {
              Object RESULT =null;
		int opeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int operight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String ope = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int datoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int datoright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Dato dato = (Dato)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("FUN",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // GRA ::= graficar parentesisA cadena coma cadena coma identificador coma cadena coma cadena parentesisC puntocoma 
            {
              String RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("GRA",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-12)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // DATOS ::= num 
            {
              Dato RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String num = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		Dato dat = new Dato(0,"",Integer.parseInt(num),0); RESULT = dat;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DATOS",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // DATOS ::= decimal 
            {
              Dato RESULT =null;
		int decleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int decright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String dec = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		Dato dat = new Dato(1,"",0,Double.parseDouble(dec)); RESULT = dat;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DATOS",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // DATOS ::= cadena 
            {
              Dato RESULT =null;
		int cadleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cadright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String cad = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		Dato dat = new Dato(2,cad,0,0); RESULT = dat;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DATOS",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // OPERADOR ::= menor 
            {
              String RESULT =null;
		 RESULT = "0"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPERADOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // OPERADOR ::= mayor 
            {
              String RESULT =null;
		 RESULT = "1"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPERADOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // OPERADOR ::= menorigual 
            {
              String RESULT =null;
		 RESULT = "2"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPERADOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // OPERADOR ::= mayorigual 
            {
              String RESULT =null;
		 RESULT = "3"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPERADOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // OPERADOR ::= igualigual 
            {
              String RESULT =null;
		 RESULT = "4"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPERADOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // OPERADOR ::= noigual 
            {
              String RESULT =null;
		 RESULT = "5"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPERADOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
