
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int coma = 4;
  public static final int puntocoma = 3;
  public static final int num = 8;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int parentesisc = 6;
  public static final int extraer = 2;
  public static final int parentesisa = 5;
  public static final int identificador = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "extraer",
  "puntocoma",
  "coma",
  "parentesisa",
  "parentesisc",
  "identificador",
  "num"
  };
}

