
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores_datos;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int corcheteA = 9;
  public static final int llaveC = 8;
  public static final int llaveA = 7;
  public static final int coma = 12;
  public static final int claves = 2;
  public static final int registros = 3;
  public static final int cadena = 5;
  public static final int decimal = 6;
  public static final int EOF = 0;
  public static final int num = 4;
  public static final int error = 1;
  public static final int corcheteC = 10;
  public static final int igual = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "claves",
  "registros",
  "num",
  "cadena",
  "decimal",
  "llaveA",
  "llaveC",
  "corcheteA",
  "corcheteC",
  "igual",
  "coma"
  };
}

